# Generated by Django 3.2.9 on 2022-01-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservas', '0004_auto_20211210_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_usuario',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='plan_usuario',
            name='id_plan',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan_usuario',
            name='url',
            field=models.CharField(default='https://elcomercio.pe/resizer/TGCsuHf4e88fBOhhEUbfaHgHs9A=/560x0/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/ZPAAAE7JYRBETISIFG3E77ZACU.png', max_length=2083, verbose_name='Url del plan'),
        ),
    ]
