# Generated by Django 3.2.9 on 2022-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservas', '0005_auto_20220119_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_usuario',
            name='duracion',
            field=models.CharField(default='45 min', max_length=50, verbose_name='Duración'),
        ),
        migrations.AlterField(
            model_name='plan_usuario',
            name='jornada',
            field=models.CharField(choices=[('Diurna', 'diurna'), ('Nocturna', 'nocturna')], default='Diurno', max_length=10, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='plan_usuario',
            name='url',
            field=models.CharField(default='https://images.squarespace-cdn.com/content/v1/59014ed8db29d637250fa476/1506798703877-DZ64MSMJEPT91MKR124C/IMG_7487.JPG?format=1500w', max_length=2083, verbose_name='Url del plan'),
        ),
    ]
