# Generated by Django 3.2.9 on 2022-01-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppReservas', '0006_auto_20220119_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_usuario',
            name='duracion',
            field=models.CharField(default='45', max_length=50, verbose_name='Duración en minutos'),
        ),
    ]
